### PR TITLE
Add dtspec and dbt-container-skeleton references

### PR DESCRIPTION
**Pull request by gnilrets**

### CODE REVIEW

**Comment by smomni** [comment]
Hi @gnilrets and thanks for the PR, interesting projects you've got there! There's quite a lot to take in but here's how I understood how dtspec and dbt work together:

1. Create dtspec source-target mapping YML files in `dtspec/`
2. Create a dtspec CLI config file `dtspec/config.yml`
3. Run `dtspec db --fetch-schemas` to generate dbt's schema YML files for the target tables
4. Run `dtspec db --init-test-db` and `dtspec test-dbt` to run dtspec tests

Is this correct? What's the benefit of defining the source-target mapping as a dtspec instead of as dbt tests?

**Comment by gnilrets** [comment]
@smomni - Great question, I did write up a discourse post on this here - https://discourse.getdbt.com/t/testing-data-transformations/733

In short, dtspec allows you to write tests that show how target data should look after transformation, given some source data.  These kinds of tests can be awkward to write with dbt test SQL.  It's also possible you might want to write a test for a data situation that doesn't yet exist in your data but you expect it may come up some time.  dtspec allows you generate fake data, load it into a test data system, run dbt, and then check that the resultant data is as you expect.

**Comment by smomni** [comment]
I hear you @gnilrets , thanks for the clarification! Can dtspec read test data from CSV or other file formats? Defining data sets in YML can be a bit cumbersome and prone to formatting errors.

**Comment by gnilrets** [comment]
Not through the CLI, but at its core, dtspec is just an API that accepts a JSON message to collect and craft the test data.  So if you can convert CSVs into JSON, you should be able to pass it to dtspec.

**Pull request merged**
